#ifndef PN7642_VERSION_INFO_H_INCLUDED
#define PN7642_VERSION_INFO_H_INCLUDED


/*----------------------------------------------------------------------------*/ 
/* Copyright 2022-2023 NXP                                                    */
/*                                                                            */
/* NXP Confidential. This software is owned or controlled by NXP and may only */
/* be used strictly in accordance with the applicable license terms.          */
/* By expressly accepting such terms or by downloading, installing,           */
/* activating and/or otherwise using the software, you are agreeing that you  */
/* have read, and that you agree to comply with and are bound by, such        */
/* license terms. If you do not agree to be bound by the applicable license   */
/* terms, then you may not retain, install, activate or otherwise use the     */
/* software.                                                                  */
/*----------------------------------------------------------------------------*/
/*
 * Version Information
 * Auto-Generated by:
 *     docs\22_rel_doc\version_update.py (v2023.02.12_00)
 *
 * Do not edit this file. Update version_info.txt instead. */
 
 
/* Component ID definition, used by tools. */
#ifndef FSL_COMPONENT_ID
#define FSL_COMPONENT_ID "driver.hal_intfs"
#endif

#define PN7642_VER_FILEDESCRIPTION    "PN7642_02.02.00_20231009"
#define PN7642_VER_FILEVERSION         2,2,0,0
#define PN7642_VER_FILEVERSION_STR    "2,2,0,0"
#define PN7642_VER_PRODUCTVERSION      2,2,0,0
#define PN7642_VER_PRODUCTVERSION_STR "2,2,0,0"
#define PN7642_VER_MAJOR          (2)
#define PN7642_VER_MINOR          (2)
#define PN7642_VER_SDK_MINOR_V    (0)


/* ______GENERATED_FROM____version_info.txt
 * # _____________________________________________________________________________
 * # Product Description
 * #
 * 
 * sw_c_define_name 	= "PN7642"
 * sw_product_name  	= "PN7642" 		# Product Name
 * sw_product_rel_date  = "20231009" 	#release date
 * sw_v_major       	= "02"       	# FW/SW Major Release NNX
 * sw_v_minor       	= "02"       	# FW/SW Minor Version
 * sdk_minor_v      	= "00"       	# SW SDK Development Version
 * sw_maturity      	= "P"        	# SW Maturity "A" Alpha, "B":Beta, "P": Production
 * sw_metastring    	= ""         	# Any meta string
 * # _____________________________________________________________________________
 * #
 * # History: Descending
 * # 02.02.00 : PN7642_02.02.00_20231009
 * #          : This FW release is compatible with FW v02.00 on NSC API addresses. The content of this FW release is same as that of FW v02.01.
 * #          : Fixed issues in Card Mode.
 * #          : Added PN76_Sys_Get_HIF_Timeout() and PN76_Sys_Set_HIF_Timeout() to set the HIF timeout value used incase of Pin-less (download, SKM boot mode)
 * #          : Added PN76_Sys_Configure_TestBus_MultipleDigital() switch multiple available digital test bus signal on selected pad configurations.
 * #		  :
 * # 02.01.00 : PN7642_02.01.00_20230901
 * #          : Fixed issues in Card Mode.
 * #          : Added PN76_Sys_Configure_TestBus_MultipleDigital()switch multiple available digital test bus signal on selected pad configurations.
 * #		  :
 * # 02.00.00 : PN7642_02.00.00_20230405
 * #          : USB compliance feature added with USB-CCID ContactLess driver
 * #          :  - Added an API PN76_Sys_Hal_USB_Suspend() to suspend the USB-CCID driver and resume of it.
 * #          : Added an API PN76_Sys_GetPartId() to get the part number of the PN76xx IC.
 * #          : Fixed an issue with chunk frame download.
 * #          : Added user configuration to store the ULPCD calibration status by application.
 * #          :
 * # 01.00.00 : PN7642_01.00.00_20221121
 * #          : Final Product FW release
 * #		  :
 * # 00.07.00 : PN7642_00.07.00_20221104
 * #          : BugFix release
 * #		  :
 * # 00.06.00 : PN7642_00.06.00_20220913
 * #          : BugFix release
 * #		  :
 * # 00.05.00 : PN7642_00.05.00_20220824
 * #          : BugFix release
 * #          :
 * # 00.04.00 : PN7642_00.00.04_20220805
 * #          : Full featured FW_RC1 release of PN7642 GOC firmware.
 * #          : For Internal use only.
 * # 	   	  : Added support for Symmetric Features, symmetric AES (CBC, ECB, CCM, CTR, GCM/GMAC,EAX), 3DES, CMAC (for AES, 3DES),Hash algorithms	SHA(256, 384, 512), Secure SHA(256, 384, 512), HMAC, HKDF (key derivation)
 * #          : Added support for Asymmetric Features,Asymmetric	ECC Key Generation, Signature generation and verification, ECDH with curves BP256r1, BP384r1, P256, P384, Custom curves, EDDSa (sign, verify), EDDSaMontDH, RSA (keygen, encrypt, decrypt, sign, verify)
 * #          : CLIF Features Reader Mode Type A (106,212,424,848),Type B (106,212,424,848),Type F(212,424),ISO15693,ISO18000p3m3
 * #          : CLIF Features Card Mode, TypeA (106,212,424,848),T4AT.
 * #          : System Drivers (Non-Secure Callable),Security Key-mode(CRC),PMU(EEPROM Interface),SMU(Register Interg=face),RNG(Testbus (Digital, Analog, CTS))
 * #	      :
 * # 00.03.00 : PN7642_00.03.00_20220726
 * #          : BugFix release for Internal Testing
 * #          :
 * # 00.02.00 : PN7642_00.02.00_20220507
 * #          : Secure Flash FW release for SDK PRE EAR integration and Internal Testing.
 * #          :
 * # 00.01.00 : PN7642_00.01.00_20220505
 * #          : Draft Release for Internal review
 * # ____________________________________________________________________________
 */


#endif /* PN7642_VERSION_INFO_H_INCLUDED */
