################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_SRCS := 
C_SRCS := 
OBJ_SRCS := 
O_SRCS := 
S_SRCS := 
S_UPPER_SRCS := 
C_DEPS := 
EXECUTABLES := 
OBJS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
NxpNfcRdlib/comps/phCryptoRng/src/Sw \
NxpNfcRdlib/comps/phCryptoRng/src \
NxpNfcRdlib/comps/phCryptoSym/src/Sw \
NxpNfcRdlib/comps/phCryptoSym/src \
NxpNfcRdlib/comps/phKeyStore/src/PN76XX \
NxpNfcRdlib/comps/phKeyStore/src/Sw \
NxpNfcRdlib/comps/phKeyStore/src \
NxpNfcRdlib/comps/phNfcLib/src \
NxpNfcRdlib/comps/phTMIUtils/src \
NxpNfcRdlib/comps/phTools/src \
NxpNfcRdlib/comps/phacDiscLoop/src/Sw \
NxpNfcRdlib/comps/phacDiscLoop/src \
NxpNfcRdlib/comps/phalFelica/src/Sw \
NxpNfcRdlib/comps/phalFelica/src \
NxpNfcRdlib/comps/phalI18000p3m3/src/Sw \
NxpNfcRdlib/comps/phalI18000p3m3/src \
NxpNfcRdlib/comps/phalICode/src/Sw \
NxpNfcRdlib/comps/phalICode/src \
NxpNfcRdlib/comps/phalMfNtag42XDna/src/Sw \
NxpNfcRdlib/comps/phalMfNtag42XDna/src \
NxpNfcRdlib/comps/phalMfc/src/Sw \
NxpNfcRdlib/comps/phalMfc/src \
NxpNfcRdlib/comps/phalMfdf/src/Sw \
NxpNfcRdlib/comps/phalMfdf/src \
NxpNfcRdlib/comps/phalMfdfEVx/src/Sw \
NxpNfcRdlib/comps/phalMfdfEVx/src \
NxpNfcRdlib/comps/phalMfdfLight/src/Sw \
NxpNfcRdlib/comps/phalMfdfLight/src \
NxpNfcRdlib/comps/phalMfpEVx/src/Sw \
NxpNfcRdlib/comps/phalMfpEVx/src \
NxpNfcRdlib/comps/phalMful/src/Sw \
NxpNfcRdlib/comps/phalMful/src \
NxpNfcRdlib/comps/phalT1T/src/Sw \
NxpNfcRdlib/comps/phalT1T/src \
NxpNfcRdlib/comps/phalTop/src/Sw \
NxpNfcRdlib/comps/phalTop/src \
NxpNfcRdlib/comps/phalVca/src/Sw \
NxpNfcRdlib/comps/phalVca/src \
NxpNfcRdlib/comps/phceT4T/src/Sw \
NxpNfcRdlib/comps/phceT4T/src \
NxpNfcRdlib/comps/phhalHw/src/PN76xx \
NxpNfcRdlib/comps/phhalHw/src \
NxpNfcRdlib/comps/phlnLlcp/src/Sw \
NxpNfcRdlib/comps/phlnLlcp/src \
NxpNfcRdlib/comps/phnpSnep/src/Sw \
NxpNfcRdlib/comps/phnpSnep/src \
NxpNfcRdlib/comps/phpalEpcUid/src/Sw \
NxpNfcRdlib/comps/phpalEpcUid/src \
NxpNfcRdlib/comps/phpalFelica/src/Sw \
NxpNfcRdlib/comps/phpalFelica/src \
NxpNfcRdlib/comps/phpalI14443p3a/src/Sw \
NxpNfcRdlib/comps/phpalI14443p3a/src \
NxpNfcRdlib/comps/phpalI14443p3b/src/Sw \
NxpNfcRdlib/comps/phpalI14443p3b/src \
NxpNfcRdlib/comps/phpalI14443p4/src/Sw \
NxpNfcRdlib/comps/phpalI14443p4/src \
NxpNfcRdlib/comps/phpalI14443p4a/src/Sw \
NxpNfcRdlib/comps/phpalI14443p4a/src \
NxpNfcRdlib/comps/phpalI14443p4mC/src/Sw \
NxpNfcRdlib/comps/phpalI14443p4mC/src \
NxpNfcRdlib/comps/phpalI18000p3m3/src/Sw \
NxpNfcRdlib/comps/phpalI18000p3m3/src \
NxpNfcRdlib/comps/phpalI18092mPI/src/Sw \
NxpNfcRdlib/comps/phpalI18092mPI/src \
NxpNfcRdlib/comps/phpalI18092mT/src/Sw \
NxpNfcRdlib/comps/phpalI18092mT/src \
NxpNfcRdlib/comps/phpalMifare/src/Sw \
NxpNfcRdlib/comps/phpalMifare/src \
NxpNfcRdlib/comps/phpalSli15693/src/Sw \
NxpNfcRdlib/comps/phpalSli15693/src \
board \
components/CLIF \
components/DAL/src/PN76xx \
components/phOsal/src/NullOs \
components/phOsal/src/NullOs/portable \
device \
drivers \
rtt/RTT \
rtt/Syscalls \
source \
startup \
utilities \

